name: Zephyr development containers (NG)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  arm:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        sdk: [0.17.1]
        toolchain: [{ arch: "arm-zephyr-eabi", nick: "arm"}]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/zephyr:${{ matrix.toolchain.nick }}-${{ matrix.sdk }}SDK
          build-args: |
            ZEPHYR_SDK_TOOLCHAINS=-t ${{ matrix.toolchain.arch }}
            ZEPHYR_SDK_VERSION=${{ matrix.sdk }}